engines:
  duplication:
      enabled: false
      checks:
        Similar code:
          enabled: false
      config:
        languages:
          - javascript
  fixme:
    enabled: true
ratings:
  paths:
    - "server/*.js"
    - "server/**/*.js"
    - "client/*.js"
    - "client/**/*.js"
exclude_paths:
  - "node_modules/"
  - "client/dist/bundle.min.js"
  - ".idea"
