language: node_js
branches:
  only:
    - master
node_js:
  - "6.10"
install:
  - npm install
script:
  - npm run test-prod
services:
  - postgresql
cache:
  - npm install
before_script:
  - npm install sequelize-cli -g
after_success:
  - nyc npm run test && nyc report --reporter=text-lcov | coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=artvBsERwCEJSNnZhixehgHIoRaBl3EYo
