language: node_js
node_js:
  - "node"
  - "6.11.1"
install: [
    "npm install -g mocha",
    "mocha install",
    "npm install",
    "chmod +x node_modules/.bin/*"
  ],
env:
- NODE_ENV=TEST
script:
  - npm test
