language: node_js
branches:
  only:
    - master
node_js:
  - "6.10"
install:
  - npm install
script:
  - npm test-prod
services:
  - postgresql
cache:
  - npm install
before_script:
  - npm install sequelize-cli -g
