apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postiit-deployment
  labels:
    #Project ID
    app: cicdtest-192020
spec:
  #Run two instances of our application
  replicas: 1
  template:
    metadata:
      labels:
        app: cicdtest-192020
    spec:
      #Container details
      containers:
        - name: node-app
          image: gcr.io/cicdtest-192020/node-app:0.0.1
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 3000
          env:
          # Name of the environment variable as will be in the Pod
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-secret
                    # key of the value stored in the secret
                    key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-secret
                    # key of the value stored in the secret
                    key: JWT_SECRET
            - name: EMAIL_NAME
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-secret
                    # key of the value stored in the secret
                    key: EMAIL_NAME
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-secret
                    # key of the value stored in the secret
                    key: EMAIL_PASSWORD
            - name: SMS_API_KEY
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-secret
                    # key of the value stored in the secret
                    key: SMS_API_KEY
            - name: SMS_API_SECRET
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-secret
                    # key of the value stored in the secret
                    key: SMS_API_SECRET