// define constants
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const CREATE_GROUP = 'CREATE_GROUP';
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const SEARCH_ALL_USERS = 'SEARCH_ALL_USERS';
export const GET_GROUPS_CREATED_BY_USER = 'GET_GROUPS_CREATED_BY_USER';
export const ADD_USER_TO_GROUPS = 'ADD_USER_TO_GROUPS';
export const GET_USERS_IN_GROUP = 'GET_USERS_IN_GROUP';
export const COMPOSE_MESSAGE = 'COMPOSE_MESSAGE';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const RETRIEVE_MESSAGE = 'RETRIEVE_MESSAGE';
export const USERS_WHO_HAVE_READ_MESSAGE = 'USERS_WHO_HAVE_READ_MESSAGE';
